/*******************************************************************************
 * Copyright (c) 2017 ,ENSENTEC
 * All rights reserved.
 * FileName e-stop.h
 * Data     2018-2-5 10:26:41
 * The Eclipse Public License is available at
 * http://www.ensentec.com
 * 
 * Contributors     tianqf@ensentec.com
 *******************************************************************************/
#ifndef E_STOP_SWITCH_INCLUDE
#define E_STOP_SWITCH_INCLUDE

void E_STOP_init(void);
void Check_estop(void);

#endif
